# Generated by Django 6.0.4 on 2026-04-27 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inventario', models.CharField(max_length=50, unique=True)),
                ('caracteristicas', models.TextField()),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_uso', models.CharField(max_length=100)),
                ('costo_registrado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_adicionales', models.TextField(blank=True, null=True)),
                ('observaciones_encargado', models.TextField(blank=True, null=True)),
                ('foto_inmueble', models.ImageField(blank=True, null=True, upload_to='inmuebles/')),
                ('foto_etiqueta', models.ImageField(blank=True, null=True, upload_to='etiquetas/')),
            ],
        ),
    ]
